# This docker-compose file is used to run the project's published image
#
# Usage: docker-compose up [-d]
#
# See comment in docker-compose.dev.yml if you want to run for development.

version: '3.4'

networks:
  reaction:
    external:
      name: reaction.localhost

services:
  identity:
    image: reactioncommerce/identity:3.3.0
    env_file:
      - ./.env
    networks:
      default:
      reaction:
    ports:
      - "4100:4100"
